name: flutter_test_extensions
description: Extensions to speed up and save on code when writing widget, and integration tests
version: 0.0.1-beta
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  austerity: ^0.0.5-beta
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
